smallrye:
  config:
    mapping:
      validate-unknown: false # ignore unknown config properties

# configure production datasource
"%prod":
  quarkus:
    datasource:
      db-kind: postgresql
      #username: one-stop
      #password: password
      jdbc:
        url: jdbc:postgresql://db:5432/one-stop

quarkus:
  flyway:
    migrate-at-start: true
