quarkus:
  native:
    resources:
      includes: "templates/**"

one-stop:
  email:
    disabled: false

    common-args:
      COMPANY_LONG_NAME: Hillayes One-Stop
      COMPANY_COPYRIGHT_NAME: One-Stop
      COMPANY_CONTACT_EMAIL: watson.phill+onestop@gmail.com
      COMPANY_ADDRESS_LINE1: Hillayes
      COMPANY_ADDRESS_LINE2: Hullavington
      COMPANY_ADDRESS_LINE3: Wiltshire SN14

    default-sender:
      name: ${one-stop.email.common-args.COMPANY_LONG_NAME}
      email: ${one-stop.email.common-args.COMPANY_CONTACT_EMAIL}
      locale: "en"

    templates:
      header:
        en:
          subject: not-applicable
          template: "header/en.html"

      event-hospital:
        recipient:
          name: "Administrator"
          email: "watson.phill+onestop@gmail.com"
          locale: "en"
        en:
          subject: "An event has failed to be processed"
          template: "event-hospital/en.html"

      user-registered:
        en:
          subject: "Hi $user.preferredName$, please complete your One-Stop registration"
          template: "user-registered/en.html"
        fr:
          subject: "Salut $user.preferredName$, veuillez compléter votre inscription One-Stop"
          template: "user-registered/fr.html"

      user-created:
        en:
          subject: "Welcome to One-Stop $user.preferredName$"
          template: "user-created/en.html"

      user-updated:
        en:
          subject: "Your account has been updated"
          template: "user-updated/en.html"

      user-deleted:
        en:
          subject: "Sorry to see you go"
          template: "user-deleted/en.html"

      account-activity:
        en:
          subject: "Activity on your One-Stop account"
          template: "account-activity/en.html"

      audit-issue-found:
        en:
          subject: "An issue has been found with transactions your account"
          template: "audit-issue-found/en.html"

      new-oidc-login:
        en:
          subject: "New authentication on your One-Stop account"
          template: "new-oidc-login/en.html"

      consent-given:
        en:
          subject: "Your One-Stop access to $event.institutionName$"
          template: "consent-given/en.html"

      consent-denied:
        en:
          subject: "Your One-Stop access to $event.institutionName$"
          template: "consent-denied/en.html"

      consent-cancelled:
        en:
          subject: "Your One-Stop access to $event.institutionName$"
          template: "consent-cancelled/en.html"

      consent-suspended:
        en:
          subject: "Your One-Stop access to $event.institutionName$"
          template: "consent-suspended/en.html"

      consent-expired:
        en:
          subject: "Your One-Stop access to $event.institutionName$"
          template: "consent-expired/en.html"

  notification:
    common-args:
      COMPANY_LONG_NAME: ${one-stop.email.common-args.COMPANY_LONG_NAME}
      COMPANY_COPYRIGHT_NAME: ${one-stop.email.common-args.COMPANY_COPYRIGHT_NAME}

    templates:
      consent-denied:
        en: "Access to $event.institutionName$ has been denied.\nReason given '$event.errorDetail$'."
      consent-suspended:
        en: "Access to $event.institutionName$ has been suspended.\nYou need to renew your consent."
      consent-expired:
        en: "Access to $event.institutionName$ has expired.\nYou need to renew your consent."
      consent-timeout:
        en: "Your consent registration for $event.institutionName$ has timed out.\nYou can try to register again."
      account-activity:
        en: "$activity$"
      audit-issue-found:
        en: "An issue has been found with transactions your account.\nPlease contact us."

  scheduler:
    schema: ${quarkus.hibernate-orm.database.default-schema}
    tasks:
      # jobbing tasks to queue emails for sending
      queue-email:
        on-failure: # gives a max of 16 minutes
          max-retry: 4
          retry-interval: PT2M
          retry-exponent: 1.5
