quarkus:
  log:
    min-level: TRACE
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,S} %-5p %X{correlationId} - [%c{3.}] (%t) %s%e%n"
    category:
      "org.apache.kafka":
        level: WARN
      "com.hillayes":
        level: TRACE
