smallrye:
  config:
    mapping:
      validate-unknown: false # ignore unknown config properties

# configure production datasource
"%prod":
  quarkus:
    datasource:
      db-kind: postgresql
      #username: one-stop
      #password: password
      jdbc:
        url: jdbc:postgresql://db:5432/one-stop

quarkus:
  hibernate-orm:
    database:
      default-schema: users

  flyway:
    migrate-at-start: true
    schemas: ${quarkus.hibernate-orm.database.default-schema}

  log:
    min-level: TRACE
    level: INFO
    console:
      format: '%d{yyyy-MM-dd HH:mm:ss,S} %-5p %X{correlationId} - [%c{3.}] (%t) %s%e%n'
    category:
      "io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator":
        level: INFO
      "org.jose4j.jwk":
        level: INFO
      "org.apache.kafka":
        level: WARN
      "com.hillayes":
        level: DEBUG

one-stop:
  auth:
    onboarding:
      token-expires-in: 'PT15M'
