#smallrye:
#  jwt:
#    verify:
#      key:
#        location: auth/publicKey.pem
#    sign:
#      key:
#        location: auth/privateKey.pem

mp:
  jwt:
    verify:
      audiences: com.hillayes
      issuer: https://hillayes.com/one-stop
      publickey:
        location: http://user-service:8080/api/v1/auth/jwks.json
    token:
      header: Cookie
      cookie: 'access_token'

smallrye:
  jwt:
    jwks:
      refresh-interval: 15
      forced-refresh-interval: 5

# configure production datasource
"%prod":
  quarkus:
    datasource:
      db-kind: postgresql
      #username: one-stop
      #password: password
      jdbc:
        url: jdbc:postgresql://db:5432/one-stop

quarkus:
  native:
    # defines which resources are included in native image
    resources:
      includes: auth/**

  flyway:
    migrate-at-start: true
    schemas: users

  hibernate-orm:
    database:
      default-schema: users

  log:
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,S} %-5p %X{correlationId} - [%c{3.}] (%t) %s%e%n"
    category:
      "com.hillayes":
        level: DEBUG
      "io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator":
        level: TRACE

one-stop:
  jwt:
    access-token:
      duration-secs: 300
    refresh-token:
      cookie: 'refresh_token'
      duration-secs: 1800
  jwk:
    set-size: 2
  xsrf:
    cookie-name: 'XSRF-TOKEN'
    header-name: 'X-XSRF-TOKEN'
    duration-secs: 1800
    # secret: 'this will be passed in'
