mp:
  jwt:
    verify:
      audiences: com.hillayes
      issuer: https://hillayes.com/one-stop
      publickey:
        location: http://user-service:8080/api/v1/auth/jwks.json
    token:
      header: Cookie
      cookie: 'access_token'

smallrye:
  jwt:
    jwks:
      refresh-interval: 15
      forced-refresh-interval: 5

# configure production datasource
"%prod":
  quarkus:
    datasource:
      db-kind: postgresql
      #username: one-stop
      #password: password
      jdbc:
        url: jdbc:postgresql://db:5432/one-stop

quarkus:
  flyway:
    migrate-at-start: true
    schemas: users

  hibernate-orm:
    database:
      default-schema: users

  log:
    min-level: TRACE
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,S} %-5p %X{correlationId} - [%c{3.}] (%t) %s%e%n"
    category:
      "io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator":
        level: INFO
      "com.hillayes":
        level: DEBUG

one-stop:
  jwt:
    access-token:
      duration-secs: 300
    refresh-token:
      cookie: 'refresh_token'
      duration-secs: 1800
  jwk:
    set-size: 2
  auth:
    xsrf:
      cookie-name: 'XSRF-TOKEN'
      header-name: 'X-XSRF-TOKEN'
      duration-secs: 1800
      # secret: 'this will be passed in via docker env'
"%test":
  one-stop:
    auth:
      xsrf:
        secret: this is a secret for xsrf tokens
