smallrye:
  jwt:
    verify:
      key:
        location: auth/publicKey.pem
    sign:
      key:
        location: auth/privateKey.pem

mp:
  jwt:
    token:
      header: Cookie
      cookie: 'access_token'
    verify:
      issuer: https://hillayes.com/one-stop

quarkus:
  native:
    resources:
      includes: auth/**

  # configure datasource
  datasource:
    db-kind: postgresql
    username: one-stop
    password: password
    jdbc:
      url: jdbc:postgresql://db:5432/one-stop

  flyway:
    migrate-at-start: true
    schemas: users

  hibernate-orm:
    database:
      default-schema: users

  log:
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,S} %-5p %X{correlationId} - [%c{3.}] (%t) %s%e%n"
    category:
      "com.hillayes":
        level: DEBUG

one-stop:
  jwt:
    refresh-token:
      cookie: 'refresh_token'
      duration-secs: 1800