mp:
  jwt:
    verify:
      audiences: ${one-stop.auth.access-token.audiences}
      issuer: ${one-stop.auth.access-token.issuer}
      publickey:
        location: http://user-service:8080/api/v1/auth/jwks.json
    token:
      header: Cookie
      cookie: ${one-stop.auth.access-token.cookie}

smallrye:
  config:
    mapping:
      validate-unknown: false # ignore unknown config properties

  jwt:
    jwks:
      refresh-interval: 15
      forced-refresh-interval: 5

# configure production datasource
"%prod":
  quarkus:
    datasource:
      db-kind: postgresql
      #username: one-stop
      #password: password
      jdbc:
        url: jdbc:postgresql://db:5432/one-stop

quarkus:
  flyway:
    migrate-at-start: true
    schemas: users

  hibernate-orm:
    database:
      default-schema: users

  rest-client:
    google-api:
      url: https://oauth2.googleapis.com

  log:
    min-level: TRACE
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,S} %-5p %X{correlationId} - [%c{3.}] (%t) %s%e%n"
    category:
      "io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator":
        level: INFO
      "org.jose4j.jwk":
        level: INFO
      "org.apache.kafka":
        level: WARN
      "com.hillayes":
        level: DEBUG

one-stop:
  auth:
    access-token:
      cookie: 'access_token'
      issuer: https://hillayes.com/one-stop
      audiences: com.hillayes
      duration-secs: 300
    refresh-token:
      cookie: 'refresh_token'
      duration-secs: 1800
    jwk:
      set-size: 2
      rotation-interval: ${one-stop.auth.refresh-token.duration-secs}
    xsrf:
      cookie-name: 'XSRF-TOKEN'
      header-name: 'X-XSRF-TOKEN'
      # secret: 'this will be passed in via docker env'

    openid:
      GOOGLE:
        config-uri: 'https://accounts.google.com/.well-known/openid-configuration'
        client-id: '284564870769-e3qm0g1dgim9kjd1gp3qmia610evn88a.apps.googleusercontent.com'
        redirect-uri: 'http://localhost/api/v1/auth/validate/google'
        # client-secret: 'this will be passed in via docker env'

      APPLE:
        config-uri: 'https://appleid.apple.com/.well-known/openid-configuration'
        team-id: 'my-apple-team-id'
        client-id: 'my-apple-registered-client-id'
        redirect-uri: 'http://localhost/api/v1/auth/validate/apple'
        # key-id: 'this will be passed in via docker env'
        # private-key: 'this will be passed in via docker env'
