quarkus:

  # configure datasource
  datasource:
    db-kind: postgresql
    username: one-stop
    password: password
    jdbc:
      url: jdbc:postgresql://db:5432/one-stop

  flyway:
    migrate-at-start: true
    schemas: users

  hibernate-orm:
    database:
      default-schema: users

  log:
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,S} %-5p %X{correlationId} - [%c{3.}] (%t) %s%e%n"
    category:
      "com.hillayes":
        level: DEBUG

one-stop:
