one-stop:
  auth:
    openid:
      GOOGLE:
        config-uri: 'https://accounts.google.com/.well-known/openid-configuration'
        client-id: '284564870769-e3qm0g1dgim9kjd1gp3qmia610evn88a.apps.googleusercontent.com'
        redirect-uri: 'http://localhost/api/v1/auth/validate/google'
        # client-secret: 'this will be passed in via docker env'

      GITHUB:
        config-uri: 'https://token.actions.githubusercontent.com/.well-known/openid-configuration'
        authorization-endpoint: 'https://github.com/login/oauth/authorize'
        token-endpoint: 'https://github.com/login/oauth/access_token'
        client-id: 'Iv1.275574754910606b'
        redirect-uri: 'http://localhost/api/v1/auth/validate/github'
        # client-secret: 'this will be passed in via docker env'

      GITLAB:
        config-uri: 'https://gitlab.com/.well-known/openid-configuration'
        client-id: '31673b3e2b7f9ab7992084452b178b45609b93278f77f4d312ad1cf6d246b981'
        redirect-uri: 'http://localhost/api/v1/auth/validate/gitlab'
        # client-secret: 'this will be passed in via docker env'

      APPLE:
        config-uri: 'https://appleid.apple.com/.well-known/openid-configuration'
        team-id: 'my-apple-team-id'
        client-id: 'my-apple-registered-client-id'
        redirect-uri: 'http://localhost/api/v1/auth/validate/apple'
        # key-id: 'this will be passed in via docker env'
        # private-key: 'this will be passed in via docker env'
