one-stop:
  auth:
    openid:
      google:
        config-uri: 'https://accounts.google.com/.well-known/openid-configuration'
        redirect-uri: 'http://localhost/api/v1/auth/validate/google'
        # client-id: 'this will be passed in via docker env'
        # client-secret: 'this will be passed in via docker env'

      github:
        config-uri: 'https://token.actions.githubusercontent.com/.well-known/openid-configuration'
        authorization-endpoint: 'https://github.com/login/oauth/authorize'
        token-endpoint: 'https://github.com/login/oauth/access_token'
        redirect-uri: 'http://localhost/api/v1/auth/validate/github'
        # client-id: 'this will be passed in via docker env'
        # client-secret: 'this will be passed in via docker env'

      gitlab:
        config-uri: 'https://gitlab.com/.well-known/openid-configuration'
        redirect-uri: 'http://localhost/api/v1/auth/validate/gitlab'
        # client-id: 'this will be passed in via docker env'
        # client-secret: 'this will be passed in via docker env'

      linkedin:
        config-uri: 'https://www.linkedin.com/oauth/.well-known/openid-configuration'
        redirect-uri: 'http://localhost/api/v1/auth/validate/linkedin'
        # client-id: 'this will be passed in via docker env'
        # client-secret: 'this will be passed in via docker env'

      apple:
        config-uri: 'https://appleid.apple.com/.well-known/openid-configuration'
        team-id: 'my-apple-team-id'
        redirect-uri: 'http://localhost/api/v1/auth/validate/apple'
        # client-id: 'this will be passed in via docker env'
        # key-id: 'this will be passed in via docker env'
        # private-key: 'this will be passed in via docker env'
