mp:
  jwt:
    verify:
      audiences: ${one-stop.auth.access-token.audiences}
      issuer: ${one-stop.auth.access-token.issuer}
      publickey:
        location: http://user-service:8080/api/v1/auth/jwks.json
    token:
      header: Cookie
      cookie: ${one-stop.auth.access-token.cookie}

smallrye:
  jwt:
    jwks:
      refresh-interval: 15
      forced-refresh-interval: 5

# configure production datasource
"%prod":
  quarkus:
    datasource:
      db-kind: postgresql
      #username: one-stop
      #password: password
      jdbc:
        url: jdbc:postgresql://db:5432/one-stop

quarkus:
  flyway:
    migrate-at-start: true
    schemas: rails

  hibernate-orm:
    database:
      default-schema: rails

  rest-client:
    nordigen-api:
      url: https://ob.nordigen.com

  log:
    min-level: TRACE
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,S} %-5p %X{correlationId} - [%c{3.}] (%t) %s%e%n"
    category:
      "io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator":
        level: INFO
      "org.jose4j.jwk":
        level: INFO
      "org.apache.kafka":
        level: WARN
      "com.hillayes":
        level: DEBUG

one-stop:
  rail:
    # callback-url: http://{{host-ip}}:9876/api/v1/rails/consents/response

    countries:
      - id: GB
        name: Great Britain
      - id: DE
        name: Germany
      - id: FR
        name: France
      - id: IT
        name: Italy

    caches: # the duration of various caches - specified as Duration string
      institutions: PT6H
      account-details: PT5H

    scheduler:
      schema: rails
      tasks:
        # nightly task to refresh all account details
        poll-all-accounts:
          frequency:
            time-of-day: "02:00:00"
          on-failure:
            max-retry: 3
            retry-interval: PT1M

        # jobbing tasks to refresh the identified account details
        poll-account:
          on-failure: # gives a max of 4 hours 53 minutes
            max-retry: 15
            retry-interval: PT1M
            retry-exponent: 1.5

  auth:
    access-token:
      cookie: 'access_token'
      issuer: https://hillayes.com/one-stop
      audiences: com.hillayes
    refresh-token:
      cookie: 'refresh_token'
      duration-secs: 1800
    xsrf:
      cookie-name: 'XSRF-TOKEN'
      header-name: 'X-XSRF-TOKEN'
      # secret: 'this will be passed in via docker env'
