smallrye:
  jwt:
    verify:
      key:
        location: auth/publicKey.pem
#    sign:
#      key:
#        location: auth/privateKey.pem

mp:
  jwt:
    token:
      header: Cookie
      cookie: 'access_token'
#    verify:
#      issuer: https://hillayes.com/one-stop

quarkus:

  # configure datasource
  datasource:
    db-kind: postgresql
    username: one-stop
    password: password
    jdbc:
      url: jdbc:postgresql://db:5432/one-stop

  flyway:
    migrate-at-start: true
    schemas: rails

  hibernate-orm:
    database:
      default-schema: rails

  rest-client:
    nordigen-api:
      url: https://ob.nordigen.com

  log:
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,S} %-5p %X{correlationId} - [%c{3.}] (%t) %s%e%n"
    category:
      "com.hillayes":
        level: DEBUG

one-stop:
  # callback-url: /api/v1/consents/accepted

  countries:
    - id: GB
      name: Great Britain
    - id: DE
      name: Germany
    - id: FR
      name: France
    - id: IT
      name: Italy
