# configure production datasource
"%prod":
  quarkus:
    datasource:
      db-kind: postgresql
      #username: one-stop
      #password: password
      jdbc:
        url: jdbc:postgresql://db:5432/one-stop

quarkus:
  flyway:
    migrate-at-start: true
    schemas: emails

  hibernate-orm:
    database:
      default-schema: emails

  log:
    min-level: TRACE
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,S} %-5p %X{correlationId} - [%c{3.}] (%t) %s%e%n"
    category:
      "org.apache.kafka":
        level: WARN
      "com.hillayes":
        level: DEBUG

one-stop:
  email:
    disabled: false

    common-args:
      COMPANY_LONG_NAME: Hillayes One-Stop
      COMPANY_COPYRIGHT_NAME: One-Stop
      COMPANY_CONTACT_EMAIL: watson.phill+onestop@gmail.com
      COMPANY_ADDRESS_LINE1: Hillayes
      COMPANY_ADDRESS_LINE2: Hullavington
      COMPANY_ADDRESS_LINE3: Wiltshire SN14

    default-sender:
      name: ${one-stop.email.common-args.COMPANY_LONG_NAME}
      email: ${one-stop.email.common-args.COMPANY_CONTACT_EMAIL}
      locale: "en"

    templates:
      header:
        en:
          subject: not-applicable
          template: "header/en.html"

      user-registered:
        en:
          subject: "Hi $user.preferredName$, please complete your One-Stop registration"
          template: "user-registered/en.html"
        fr:
          subject: "Salut $user.preferredName$, veuillez compléter votre inscription One-Stop"
          template: "user-registered/fr.html"

      user-created:
        en:
          subject: "Welcome to OneStop $user.preferredName$"
          template: "user-created/en.html"

      user-updated:
        en:
          subject: "Your account has been updated"
          template: "user-updated/en.html"

      user-deleted:
        en:
          subject: "Sorry to see you go"
          template: "user-deleted/en.html"

      account-activity:
        en:
          subject: "Activity on your OneStop account"
          template: "account-activity/en.html"

      consent-given:
        en:
          subject: "Your OneStop access to $event.institutionName$"
          template: "consent-given/en.html"

      consent-denied:
        en:
          subject: "Your OneStop access to $event.institutionName$"
          template: "consent-denied/en.html"

      consent-cancelled:
        en:
          subject: "Your OneStop access to $event.institutionName$"
          template: "consent-cancelled/en.html"

      consent-suspended:
        en:
          subject: "Your OneStop access to $event.institutionName$"
          template: "consent-suspended/en.html"

      consent-expired:
        en:
          subject: "Your OneStop access to $event.institutionName$"
          template: "consent-expired/en.html"
