# configure production datasource
"%prod":
  quarkus:
    datasource:
      db-kind: postgresql
      #username: one-stop
      #password: password
      jdbc:
        url: jdbc:postgresql://db:5432/one-stop

quarkus:
  flyway:
    migrate-at-start: true
    schemas: emails

  hibernate-orm:
    database:
      default-schema: emails

  log:
    min-level: TRACE
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,S} %-5p %X{correlationId} - [%c{3.}] (%t) %s%e%n"
    category:
      "org.apache.kafka":
        level: WARN
      "com.hillayes":
        level: DEBUG

one-stop:
  email:
    disabled: false
    default-sender:
      name: "One Stop"
      email: "watson.phill+onestop@gmail.com"
      locale: "en-GB"
    templates:
      user-registered:
        "en":
          subject: "Please complete your registration"
          template: "user-registered/en.html"
        "fr-FR":
          subject: "Veuillez compléter votre inscription"
          template: "user-registered/fr.html"

      user-created:
        "en":
          subject: "Welcome to One Stop"
          template: "user-created/en.html"

      user-updated:
        "en":
          subject: "You account has been updated"
          template: "user-updated/en.html"

      user-deleted:
        "en":
          subject: "Sorry to see you go"
          template: "user-deleted/en.html"
