# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

# to login to the github container repo use:
#    docker login https://ghcr.io -u phillwatson -p <personal-access-token>
# where:
#  <personal-access-token> is created here https://github.com/settings/tokens
# This will create an auth entry in the ~/.docker/config.json/

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  QUARKUS_CONTAINER_IMAGE_REGISTRY: ${{ REGISTRY }}
  QUARKUS_CONTAINER_IMAGE_GROUP: ${{ github.repository_owner }}
  QUARKUS_CONTAINER_IMAGE_PUSH: true

jobs:
  build:
    name: test and package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Maven
      run: |
        mvn -B install -Pclient -Ptest --file pom.xml \
          -Dquarkus.hibernate-orm.log.sql=false \
          -Dquarkus.hibernate-orm.log.bind-parameters=false \
          -Dquarkus.log.category.\"org.apache.http.wire\".level=ERROR \
          -DskipITs

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Client Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: client/
        push: true
        tags: ${{ github.repository_owner }}/client:1.0.0-SNAPSHOT
        labels: ${{ steps.meta.outputs.labels }}
